apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: opengrok
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --http-address=0.0.0.0:4180
        - --redirect-url=https://opengrok.vips.vistaprint.io/oauth2/callback
        - --oidc-issuer-url=https://cimpress.auth0.com/
        - --login-url=https://cimpress.auth0.com/authorize
        - --redeem-url=https://oauth.cimpress.io/v2/token
        - --validate-url=https://cimpress.auth0.com/userinfo
        - --email-domain=*
        - --upstream=file:///dev/null
        - --set-authorization-header=true
        - --skip-provider-button=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth0-secrets
              key: OAUTH2_PROXY_CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth0-secrets
              key: OAUTH2_PROXY_CLIENT_SECRET
        # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: auth0-secrets
              key: OAUTH2_PROXY_COOKIE_SECRET
        image: bitnami/oauth2-proxy
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
